package com.polli.android.platform

import org.thoughtcrime.securesms.AttachContactActivity
import org.thoughtcrime.securesms.ContactMultiSelectionActivity
import org.thoughtcrime.securesms.ContactSelectionListFragment
import org.thoughtcrime.securesms.LogViewActivity
import org.thoughtcrime.securesms.MuteDialog
import org.thoughtcrime.securesms.qr.BackupTransferActivity
import org.thoughtcrime.securesms.qr.RegistrationQrActivity
import org.thoughtcrime.securesms.scribbles.ScribbleActivity

typealias LegacyAttachContactActivity = AttachContactActivity
typealias LegacyContactMultiSelectionActivity = ContactMultiSelectionActivity
typealias LegacyContactSelectionListFragment = ContactSelectionListFragment
typealias LegacyLogViewActivity = LogViewActivity
typealias LegacyMuteDialog = MuteDialog
typealias LegacyBackupTransferActivity = BackupTransferActivity
typealias LegacyRegistrationQrActivity = RegistrationQrActivity
typealias LegacyScribbleActivity = ScribbleActivity
