package com.polli.android.platform

import org.thoughtcrime.securesms.AttachContactActivity
import org.thoughtcrime.securesms.ContactMultiSelectionActivity
import org.thoughtcrime.securesms.ContactSelectionListFragment
import org.thoughtcrime.securesms.scribbles.ScribbleActivity

typealias LegacyAttachContactActivity = AttachContactActivity
typealias LegacyContactMultiSelectionActivity = ContactMultiSelectionActivity
typealias LegacyContactSelectionListFragment = ContactSelectionListFragment
typealias LegacyScribbleActivity = ScribbleActivity
