package com.polli.android.platform

import com.polli.android.components.audioplay.AudioPlaybackState
import com.polli.android.components.audioplay.AudioPlaybackViewModel
import com.polli.android.components.audioplay.ChatAudioQueueProvider
import com.polli.android.service.AudioPlaybackService

typealias PolliAudioPlaybackViewModel = AudioPlaybackViewModel
typealias PolliAudioPlaybackState = AudioPlaybackState
typealias PolliPlaybackStatus = AudioPlaybackState.PlaybackStatus
typealias PolliChatAudioQueueProvider = ChatAudioQueueProvider
typealias PolliAudioPlaybackService = AudioPlaybackService
